;;; Automatically generated by private/make-alias-libraries.ss
(library (xitomatl srfi \x32;7)
  (export random-integer random-real default-random-source
    make-random-source random-source?
    random-source-state-ref random-source-state-set!
    random-source-randomize! random-source-pseudo-randomize!
    random-source-make-integers random-source-make-reals)
  (import (xitomatl srfi random)))
