;;; Automatically generated by ./private/make-alias-libraries.ss
(library (srfi \x33;7)
  (export args-fold option option? option-names
    option-required-arg? option-optional-arg?
    option-processor)
  (import (srfi args-fold)))
