;;; Automatically generated by ./private/make-alias-libraries.ss
(library (srfi \x33;8)
  (export write-with-shared-structure write/ss
    read-with-shared-structure read/ss)
  (import (srfi sharing)))
