;;; Automatically generated by private/make-alias-libraries.ss
(library (xitomatl srfi \x33;8)
  (export write-with-shared-structure write/ss
    read-with-shared-structure read/ss)
  (import (xitomatl srfi sharing)))
