;;; Automatically generated by private/make-alias-libraries.ss
(library (xitomatl srfi \x36;)
  (export open-input-string open-output-string
    get-output-string)
  (import (xitomatl srfi string-ports)))
